onlinestore/urls.py
from django.conf.urls import url
from django.urls import path, include
from shop import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='mainpage'),
    path('shop/', include('shop.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include(('payment.urls', 'payment'), namespace='payment')),
    path('admin/', admin.site.urls),
    url(r'^orders/', include(('orders.urls', 'orders'), namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^myorders/$', views.show_my_orders, name='show_orders'),
]

shop/urls.py
from django.urls import path, re_path
from shop import views

urlpatterns = [
	path('', views.index, name = 'index'),
	re_path(r'^product/(?P<product_name_slug>[\w\-]+)/$', views.show_product, name = 'show_product'),
	re_path(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name = 'show_category'),
	re_path(r'^register/$', views.RegisterFormView.as_view(), name = 'register'),
	re_path(r'^login/$', views.LoginFormView.as_view(), name = 'login'),
	re_path(r'^logout/$', views.LogoutView.as_view(), name = 'logout'),
	re_path(r'^cart/$', views.cart_detail, name = 'cart'),
	re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
	re_path(r'^clean/$', views.cart_remove_all, name='cart_remove_all'),
]

shop/models.py
from django.db import models
from django.template.defaultfilters import slugify
from decimal import Decimal
from django.conf import settings
from cloudinary.models import CloudinaryField


class Category(models.Model):
    c_name = models.CharField(max_length=80)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.c_name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.c_name

    class Meta:
        verbose_name_plural = 'Categories'


class Product(models.Model):
    p_name = models.CharField(max_length=80)
    p_price = models.IntegerField()
    p_description = models.TextField(max_length=140)
    image = CloudinaryField('image')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ('p_name',)
        index_together = (('id', 'slug'),)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.p_name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.p_name


class Cart(models.Model):

        def __init__(self, request):
            """
            Инициализируем корзину
            """
            self.session = request.session
            cart = self.session.get(settings.CART_SESSION_ID)
            if not cart:
                # save an empty cart in the session
                cart = self.session[settings.CART_SESSION_ID] = {}
            self.cart = cart

        def add(self, product, quantity=1, update_quantity=False):
            """
            Добавить продукт в корзину или обновить его количество.
            """
            product_id = str(product.id)
            if product_id not in self.cart:
                self.cart[product_id] = {'quantity': 0,
                                         'price': str(product.p_price)}
            if update_quantity:
                self.cart[product_id]['quantity'] = quantity
            else:
                self.cart[product_id]['quantity'] += quantity
            self.save()

        def save(self):
            # Обновление сессии cart
            self.session[settings.CART_SESSION_ID] = self.cart
            # Отметить сеанс как "измененный", чтобы убедиться, что он сохранен
            self.session.modified = True

        def remove(self, product):
            """
            Удаление товара из корзины.
            """
            product_id = str(product.id)
            if product_id in self.cart:
                del self.cart[product_id]
                self.save()

        def __iter__(self):
            """
            Перебор элементов в корзине и получение продуктов из базы данных.
            """
            product_ids = self.cart.keys()
            # получение объектов product и добавление их в корзину
            products = Product.objects.filter(id__in=product_ids)
            for product in products:
                self.cart[str(product.id)]['product'] = product

            for item in self.cart.values():
                item['price'] = Decimal(item['price'])
                item['total_price'] = item['price'] * item['quantity']
                yield item

        def __len__(self):
            """
            Подсчет всех товаров в корзине.
            """
            return sum(item['quantity'] for item in self.cart.values())

        def get_total_price(self):
            """
            Подсчет стоимости товаров в корзине.
            """
            return sum(Decimal(item['price']) * item['quantity'] for item in
                       self.cart.values())

        def clear(self):
            # удаление корзины из сессии
            del self.session[settings.CART_SESSION_ID]
            self.session.modified = True

shop/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .models import Product, Category, Cart
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login
from django.http import HttpResponseRedirect
from django.views.generic.base import View
from django.contrib.auth import logout
from .forms import CartAddProductForm

def index(request):
    allcategories = Category.objects.all()
    context = {
        'allcategories': allcategories
    }
    return render(request, 'shop/index.html', context)


def show_product(request, product_name_slug):
    context = {}
    try:
        product = Product.objects.get(slug=product_name_slug)
        context['product'] = product
    except Product.DoesNotExist:
        context['product'] = None
    cart_product_form = CartAddProductForm()
    context['cart_product_form'] = cart_product_form

    return render(request, 'shop/product.html', context)


def show_category(request, category_name_slug):
    context = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        products = Product.objects.filter(category=category)
        context['products'] = products
        context['category'] = category
    except Category.DoesNotExist:
        context['category'] = None
        context['products'] = None

    return render(request, 'shop/category.html', context)




class RegisterFormView(FormView):
    form_class = UserCreationForm

    # Ссылка, на которую будет перенаправляться пользователь в случае успешной регистрации.
    # В данном случае указана ссылка на страницу входа для зарегистрированных пользователей.
    success_url = "/shop/login/"

    # Шаблон, который будет использоваться при отображении представления.
    template_name = "shop/register.html"

    def form_valid(self, form):
        # Создаём пользователя, если данные в форму были введены корректно.
        form.save()

        # Вызываем метод базового класса
        return super(RegisterFormView, self).form_valid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm

    # Аналогично регистрации, только используем шаблон аутентификации.
    template_name = "shop/login.html"

    # В случае успеха перенаправим на главную.
    success_url = "/"

    def form_valid(self, form):
        # Получаем объект пользователя на основе введённых в форму данных.
        self.user = form.get_user()

        # Выполняем аутентификацию пользователя.
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


class LogoutView(View):
    def get(self, request):
        # Выполняем выход для пользователя, запросившего данное представление.
        logout(request)

        # После чего, перенаправляем пользователя на главную страницу.
        return HttpResponseRedirect("/")


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'shop/cart.html', {'cart': cart})


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart')


def cart_remove_all(self):
    Cart.clear(self)
    return redirect('cart')

shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <title>{% block title %}My shop{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'shop/style.css' %}" />
    <link rel="shortcut icon" href="{% static 'shop/favicon.ico' %}" type="image/x-icon">
</head>
<body class="homepage is-preload">
    <div id="page-wrapper">

			<!-- Header -->
				<div id="header-wrapper">
					<div id="header" class="container">

						<!-- Logo -->
							<h1 id="logo"><a href="/">My Shop</a></h1>

						<!-- Nav -->
							<nav id="nav">
								<ul>
									<li>
										<a href="/">Categories</a>
										<ul>{% for category in allcategories %}
											<li><a href='/shop/category/{{ category.slug }}/'>{{ category.c_name }}</a></li>
											{% endfor %}
										</ul>
									</li>

									<li><a href="{% url 'cart' %}">My Cart</a></li>

                                    {% if user.is_authenticated %}
                                    <li  class="break"><a href="{% url 'orders:show_orders' %}">My Orders</a></li>
                                    {% else %}
                                    <li  class="break"><a href="/shop/register/">My Orders</a></li>
                                    {% endif %}

                                    <li>
                                        {% if user.is_authenticated %}
                                        <a href="{% url 'orders:show_orders'%}">My Account</a>
                                        {% else %}
                                        <a href="{% url 'register' %}">My Account</a>
                                        {% endif %}
                                        <ul>
                                            <li><a href="/shop/register/">Create account</a></li>
                                            {% if user.is_authenticated %}
                                            <li><a href="{% url 'logout' %}"><i class="fa fa-user"></i> Logout</a></li>
                                            {% else %}
                                            <li><a href="/shop/login/"><i class="fa fa-user"></i> Login</a></li>
                                            {% endif %}
                                        </ul>
                                    </li>
								</ul>
							</nav>

					</div>

		<!-- Scripts -->
			<script src="{% static 'shop/jquery.min.js' %}"></script>
			<script src="{% static 'shop/jquery.dropotron.min.js' %}"></script>
			<script src="{% static 'shop/browser.min.js' %}"></script>
			<script src="{% static 'shop/breakpoints.min.js' %}"></script>
			<script src="{% static 'shop/util.js' %}"></script>
			<script src="{% static 'shop/main.js' %}"></script>
<div id="content">
    {% block content %}
    {% endblock %}
</div>

                    <!-- Cart below everything -->
				<div id="promo-wrapper">
					<section id="promo">
                        {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                        <h2>Your cart:
                        <a href="{% url 'cart' %}">
                        {{ total_items }} item{{ total_items|pluralize }},
                            ${{ cart.get_total_price }}</a></h2>
                        {% else %}
                        <h2>Your cart is empty</h2>
                        {% endif %}
                        {% endwith %}
						<a href="{% url 'cart' %}" class="button">Go to My Cart</a>
					</section>
				</div>
                </div>
    </div>
</body>
</html>

shop/templates/shop/cart.html
{% extends "shop/base.html" %}
{% load static %}
{% load cloudinary %}
{% block title %}
    Cart
{% endblock %}
{% block content %}
<section id="hero" class="container">
    <header>
        <h2>On this page you can see
        <br />
        your shopping cart</h2>
    </header>
</section>
</div>
</div>


<table>
    <thead align="center">
    <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody align="center">
    {% for item in cart %}
        {% with product=item.product %}
            <tr>
                <td>

                            {% if product.image %}
                                {% cloudinary product.image width=200 heigh=300 crop="fill" %}
                            {% endif %}
                </td>
                <td>{{ product.p_name }}</td>
                <td>{{ item.quantity }}</td>
                <td><a href="{% url 'cart_remove' product.id%}">Remove</a></td>
                <td class="num">${{ item.price }}</td>
                <td class="num">${{ item.total_price }}</td>
            </tr>
        {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Total Price:</td>
        <td colspan="4"></td>
        <td class="num"><strong>${{ cart.get_total_price }}</strong></td>
    </tr>
    </tbody>
</table>

<a href="{% url 'index' %}" class="button light">Continue shopping</a>
<a href="{% url 'cart_remove_all' %}" class="button light">Clean the Cart</a>
<a href="{% if user.is_authenticated %}
            {% url 'orders:order_create' %}
         {% else %}
            {% url 'register' %}
         {% endif %}" class="button">Checkout</a>


{% endblock %}

shop/templates/shop/category.html
{% extends "shop/base.html" %}

{% block title %}{{ category.c_name }}{% endblock %}

{% block content %}

<section id="hero" class="container">
    <header>
        <h2>This page simply lists
        <br />
        all the {{ category.c_name }} we have in the database</h2>
    </header>
</section>
</div>
</div>

			<!-- Features 1 -->
<div class="wrapper">
	<div class="container">
		<div class="row">
			{% for product in products %}
			<section class="col-6 col-12-narrower feature">
				<header>
					<h2>{{ product.p_name }}</h2>
					<h3>Price: {{ product.p_price }}</h3>
				</header>
				<p>{{ product.p_description }}</p>
				<ul class="actions">
					<a href='/shop/product/{{ product.slug }}/' class="button">Learn more about {{ product.p_name }} and see it<br></a>
				</ul>
			</section>
			{% endfor %}
		</div>
	</div>
</div>


{% endblock %}

shop/templates/shop/index.html
{% extends "shop/base.html" %}

{% block title %}MyShop{% endblock %}

{% block content %}

<section id="hero" class="container">
    <header>
        <h2>MyShop is the first website
        <br />
        that I've written using <a href='https://www.djangoproject.com'>Django Framework</a></h2>
    </header>
    <p>I hope it works</p>
    <ul class="actions">
        <li><a href="/shop/register/" class="button">Push this Big button to create a new account</a></li>
    </ul>
</section>
</div>
</div>

<!-- Features 1 -->
				<div class="wrapper">
					<div class="container">
						<div class="row">
                            {% for category in allcategories %}
							<section class="col-6 col-12-narrower feature">
								<header>
                                    <ul>
                                    <h2>{{ category.c_name }}</h2>
                                    </ul>
                                    </header>
								<p>You can buy some nice {{ category.c_name }} here <br>(No, you can't, but you can pretend that you're buying them)</p>
								<ul class="actions">
									<li><a href='/shop/category/{{ category.slug }}/' class="button">Buy {{ category.c_name }}</a></li>
								</ul>
							</section>
                            {% endfor %}
						</div>
					</div>
				</div>

{% endblock %}

shop/templates/shop/login.html
{% extends "shop/base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}

<section id="hero" class="container">
    <header>
      <h2>You can Log In here</h2>
    </header>
   <p>If you don't have an account, use <a href="/shop/register/"><strong>Create Account</strong></a> page to create one</p>
</section>
</div>
</div>

				<div id="footer-wrapper">
					<div id="footer" class="container">
<h1>Log In</h1>
  <form action="" method="post">
    {% csrf_token %}
    <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
    {{ form.as_p }}
    <button type="submit">Log in</button>
  </form>
                    </div>
                </div>

{% endblock %}

shop/templates/shop/product.html
{% extends "shop/base.html" %}

{% block title %}{{ product.p_name }}{% endblock %}
{% load static %}
{% load cloudinary %}

{% block content %}
<section id="hero" class="container">
    <header>
        <h2>This page just shows you
        <br />
        {{ product.p_name }} and tells you all I know about it</h2>
    </header>
</section>
</div>
</div>

<div class="wrapper">
					<section class="container">
						<header class="major">
							<h2>{{ product.p_name }}</h2>
							<p>Price: {{ product.p_price }}<br>Description: {{ product.p_description }}</p>
						</header>
						<div class="row features">
							<section class="col-4 col-12-narrower feature">
								{% cloudinary product.image width=200 heigh=300 crop="fill" %}
								<p>You definitely want to buy it</p>
							</section><br>
						<form action="{% url 'cart_add' product.id %}" method="post">
						{{ cart_product_form }}
						{% csrf_token %}
						<input type="submit" value="Add to cart">
						</form>
					</section>
				</div>
{% endblock %}

shop/templates/shop/register.html
{% extends "shop/base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}

<section id="hero" class="container">
    <header>
      <h2>You can create a personal account here</h2>
    </header>
   <p>If you already have one, use <a href="/shop/login/"><strong>Log In</strong></a> page to log in</p>
</section>
</div>
</div>

				<div id="footer-wrapper">
					<div id="footer" class="container">
<h1>Create a New account</h1>
  <form action="" method="post">
    {% csrf_token %}
    <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
                    </div>
                </div>

{% endblock %}